using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text.Json;
using Xunit;

namespace PocketMicReceiver.Tests;

/// <summary>
/// Cross-language protocol fixture tests. Vectors generated by tests/gen_vectors.py.
/// </summary>
public class ProtocolFixtureTest
{
    // -- Load vectors from JSON ----------------------------------------------

    private static readonly JsonDocument VectorsDoc;
    private static readonly byte[] Key;
    private static readonly byte[] Nonce;
    private static readonly byte[] V1Datagram;
    private static readonly byte[] V2Datagram;
    private static readonly byte[] ExpectedPcm;
    private static readonly byte[] ExpectedOpus;

    static ProtocolFixtureTest()
    {
        // Find the project root (walk up from bin/)
        var dir = AppContext.BaseDirectory;
        while (dir != null && !File.Exists(Path.Combine(dir, "tests", "fixtures", "vectors.json")))
            dir = Path.GetDirectoryName(dir);

        var jsonPath = Path.Combine(dir!, "tests", "fixtures", "vectors.json");
        var json = File.ReadAllText(jsonPath);
        VectorsDoc = JsonDocument.Parse(json);
        var root = VectorsDoc.RootElement;

        Key = Convert.FromHexString(root.GetProperty("key_hex").GetString()!);
        Nonce = Convert.FromHexString(root.GetProperty("nonce_hex").GetString()!);
        V1Datagram = Convert.FromHexString(root.GetProperty("v1").GetProperty("datagram_hex").GetString()!);
        V2Datagram = Convert.FromHexString(root.GetProperty("v2").GetProperty("datagram_hex").GetString()!);

        // Expected payloads
        ExpectedPcm = MakeAlternatingPayload();
        ExpectedOpus = new byte[] { 0x48, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    }

    private const ulong SessionId = 0x0102030405060708;
    private const uint Sequence = 0;
    private const int SampleRate = 48000;
    private const string PairingKey = "test-pairing-key-1234";

    private static byte[] MakeAlternatingPayload()
    {
        var b = new byte[960];
        for (int i = 0; i < 960; i++) b[i] = (byte)(i % 2);
        return b;
    }

    // -- Tests ---------------------------------------------------------------

    [Fact]
    public void Key_Derivation_Matches_Vector()
    {
        using var sha = SHA256.Create();
        var derived = sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(PairingKey));
        Assert.Equal(Key, derived);
    }

    [Fact]
    public void Nonce_Construction_Matches_Vector()
    {
        var nonce = new byte[12];
        BinaryPrimitives.WriteUInt64BigEndian(nonce.AsSpan(0, 8), SessionId);
        BinaryPrimitives.WriteUInt32BigEndian(nonce.AsSpan(8, 4), Sequence);
        Assert.Equal(Nonce, nonce);
    }

    [Fact]
    public void V1_Header_Fields_Parse_Correctly()
    {
        Assert.Equal(1000, V1Datagram.Length);
        Assert.Equal("PMIC"u8.ToArray(), V1Datagram[..4]);
        Assert.Equal(1, V1Datagram[4]); // version
        Assert.Equal(1, V1Datagram[5]); // flags (encrypted)
        Assert.Equal(24, BinaryPrimitives.ReadUInt16BigEndian(V1Datagram.AsSpan(6, 2)));
        Assert.Equal(SessionId, BinaryPrimitives.ReadUInt64BigEndian(V1Datagram.AsSpan(8, 8)));
        Assert.Equal(Sequence, BinaryPrimitives.ReadUInt32BigEndian(V1Datagram.AsSpan(16, 4)));
        Assert.Equal(SampleRate, BinaryPrimitives.ReadInt32BigEndian(V1Datagram.AsSpan(20, 4)));
    }

    [Fact]
    public void V2_Header_Fields_Parse_Correctly()
    {
        Assert.Equal(54, V2Datagram.Length); // 28 + 10 + 16
        Assert.Equal("PMIC"u8.ToArray(), V2Datagram[..4]);
        Assert.Equal(2, V2Datagram[4]); // version
        Assert.Equal(3, V2Datagram[5]); // flags (encrypted + opus)
        Assert.Equal(28, BinaryPrimitives.ReadUInt16BigEndian(V2Datagram.AsSpan(6, 2)));
        Assert.Equal(SessionId, BinaryPrimitives.ReadUInt64BigEndian(V2Datagram.AsSpan(8, 8)));
        Assert.Equal(Sequence, BinaryPrimitives.ReadUInt32BigEndian(V2Datagram.AsSpan(16, 4)));
        Assert.Equal(SampleRate, BinaryPrimitives.ReadInt32BigEndian(V2Datagram.AsSpan(20, 4)));
        Assert.Equal(10, BinaryPrimitives.ReadInt32BigEndian(V2Datagram.AsSpan(24, 4)));
    }

    [Fact]
    public void V1_Decrypt_Produces_Expected_Pcm()
    {
        using var aes = new AesGcm(Key, 16);
        var pcm = new byte[AudioPipeline.PacketPcmBytes];
        var nonce = (byte[])Nonce.Clone();

        bool ok = AudioPipeline.TryDecrypt(aes, V1Datagram, nonce, pcm,
            out var sessionId, out var sequence, out var sampleRate);

        Assert.True(ok);
        Assert.Equal(SessionId, sessionId);
        Assert.Equal(Sequence, sequence);
        Assert.Equal(SampleRate, sampleRate);
        Assert.Equal(ExpectedPcm, pcm);
    }

    [Fact]
    public void V2_Decrypt_Without_Decoder_Returns_False()
    {
        using var aes = new AesGcm(Key, 16);
        var pcm = new byte[AudioPipeline.PacketPcmBytes];
        var nonce = (byte[])Nonce.Clone();

        bool ok = AudioPipeline.TryDecrypt(aes, V2Datagram, nonce, pcm,
            out _, out _, out _);

        // Without an Opus decoder, v2 decrypt succeeds but decode fails
        Assert.False(ok);
    }

    [Fact]
    public void V1_Tampered_Header_Bit_Flip_Rejected()
    {
        using var aes = new AesGcm(Key, 16);
        var tampered = (byte[])V1Datagram.Clone();
        tampered[10] ^= 0x01; // flip bit in session ID
        var nonce = (byte[])Nonce.Clone();
        var pcm = new byte[AudioPipeline.PacketPcmBytes];

        bool ok = AudioPipeline.TryDecrypt(aes, tampered, nonce, pcm,
            out _, out _, out _);
        Assert.False(ok);
    }

    [Fact]
    public void V1_Tampered_Ciphertext_Rejected()
    {
        using var aes = new AesGcm(Key, 16);
        var tampered = (byte[])V1Datagram.Clone();
        tampered[30] ^= 0x01; // flip bit in ciphertext
        var nonce = (byte[])Nonce.Clone();
        var pcm = new byte[AudioPipeline.PacketPcmBytes];

        bool ok = AudioPipeline.TryDecrypt(aes, tampered, nonce, pcm,
            out _, out _, out _);
        Assert.False(ok);
    }

    [Fact]
    public void V1_Tampered_Tag_Rejected()
    {
        using var aes = new AesGcm(Key, 16);
        var tampered = (byte[])V1Datagram.Clone();
        tampered[^1] ^= 0x01; // flip bit in last byte (part of tag)
        var nonce = (byte[])Nonce.Clone();
        var pcm = new byte[AudioPipeline.PacketPcmBytes];

        bool ok = AudioPipeline.TryDecrypt(aes, tampered, nonce, pcm,
            out _, out _, out _);
        Assert.False(ok);
    }

    [Fact]
    public void V1_Wrong_Key_Rejected()
    {
        var wrongKey = new byte[32];
        wrongKey[0] = 0xFF;
        using var aes = new AesGcm(wrongKey, 16);
        var nonce = (byte[])Nonce.Clone();
        var pcm = new byte[AudioPipeline.PacketPcmBytes];

        bool ok = AudioPipeline.TryDecrypt(aes, V1Datagram, nonce, pcm,
            out _, out _, out _);
        Assert.False(ok);
    }

    [Fact]
    public void V1_Truncated_Payload_Rejected()
    {
        using var aes = new AesGcm(Key, 16);
        var truncated = V1Datagram[..500];
        var nonce = (byte[])Nonce.Clone();
        var pcm = new byte[AudioPipeline.PacketPcmBytes];

        bool ok = AudioPipeline.TryDecrypt(aes, truncated, nonce, pcm,
            out _, out _, out _);
        Assert.False(ok);
    }

    [Fact]
    public void V1_Wrong_Version_Rejected()
    {
        using var aes = new AesGcm(Key, 16);
        var wrong = (byte[])V1Datagram.Clone();
        wrong[4] = 3; // unsupported version
        var nonce = (byte[])Nonce.Clone();
        var pcm = new byte[AudioPipeline.PacketPcmBytes];

        bool ok = AudioPipeline.TryDecrypt(aes, wrong, nonce, pcm,
            out _, out _, out _);
        Assert.False(ok);
    }

    [Fact]
    public void V2_Tampered_Payload_Length_Rejected()
    {
        using var aes = new AesGcm(Key, 16);
        var tampered = (byte[])V2Datagram.Clone();
        tampered[24] ^= 0x01; // flip bit in payload length
        var nonce = (byte[])Nonce.Clone();
        var pcm = new byte[AudioPipeline.PacketPcmBytes];

        bool ok = AudioPipeline.TryDecrypt(aes, tampered, nonce, pcm,
            out _, out _, out _);
        Assert.False(ok);
    }

    [Fact]
    public void Nonce_Includes_Session_Id()
    {
        var nonce1 = new byte[12];
        BinaryPrimitives.WriteUInt64BigEndian(nonce1.AsSpan(0, 8), 0x0102030405060708);
        BinaryPrimitives.WriteUInt32BigEndian(nonce1.AsSpan(8, 4), 0);

        var nonce2 = new byte[12];
        BinaryPrimitives.WriteUInt64BigEndian(nonce2.AsSpan(0, 8), 0xAAAAAAAAAAAAAAAA);
        BinaryPrimitives.WriteUInt32BigEndian(nonce2.AsSpan(8, 4), 0);

        Assert.NotEqual(nonce1, nonce2);
    }

    [Fact]
    public void Nonce_Includes_Sequence()
    {
        var nonce1 = new byte[12];
        BinaryPrimitives.WriteUInt64BigEndian(nonce1.AsSpan(0, 8), SessionId);
        BinaryPrimitives.WriteUInt32BigEndian(nonce1.AsSpan(8, 4), 0);

        var nonce2 = new byte[12];
        BinaryPrimitives.WriteUInt64BigEndian(nonce2.AsSpan(0, 8), SessionId);
        BinaryPrimitives.WriteUInt32BigEndian(nonce2.AsSpan(8, 4), 1);

        Assert.NotEqual(nonce1, nonce2);
    }

    [Fact]
    public void HeaderInfo_V1_Returns_Correct_Size_And_Codec()
    {
        var (headerSize, codec) = AudioPipeline.HeaderInfo(V1Datagram);
        Assert.Equal(24, headerSize);
        Assert.Equal(AudioPipeline.Codec.Pcm, codec);
    }

    [Fact]
    public void HeaderInfo_V2_Returns_Correct_Size_And_Codec()
    {
        var (headerSize, codec) = AudioPipeline.HeaderInfo(V2Datagram);
        Assert.Equal(28, headerSize);
        Assert.Equal(AudioPipeline.Codec.Opus, codec);
    }

    [Fact]
    public void HeaderInfo_Invalid_Magic_Returns_Zero()
    {
        var bad = new byte[100];
        var (headerSize, codec) = AudioPipeline.HeaderInfo(bad);
        Assert.Equal(0, headerSize);
    }

    [Fact]
    public void V1_Decrypt_Is_Deterministic()
    {
        using var aes = new AesGcm(Key, 16);
        var nonce1 = (byte[])Nonce.Clone();
        var nonce2 = (byte[])Nonce.Clone();
        var pcm1 = new byte[AudioPipeline.PacketPcmBytes];
        var pcm2 = new byte[AudioPipeline.PacketPcmBytes];

        AudioPipeline.TryDecrypt(aes, V1Datagram, nonce1, pcm1, out _, out _, out _);
        AudioPipeline.TryDecrypt(aes, V1Datagram, nonce2, pcm2, out _, out _, out _);

        Assert.Equal(pcm1, pcm2);
    }

    [Fact]
    public void V1_No_Encryption_Flag_Rejected()
    {
        using var aes = new AesGcm(Key, 16);
        var noFlag = (byte[])V1Datagram.Clone();
        noFlag[5] = 0; // clear encrypted flag
        var nonce = (byte[])Nonce.Clone();
        var pcm = new byte[AudioPipeline.PacketPcmBytes];

        bool ok = AudioPipeline.TryDecrypt(aes, noFlag, nonce, pcm,
            out _, out _, out _);
        Assert.False(ok);
    }

    [Fact]
    public void V1_Appended_Bytes_Rejected()
    {
        using var aes = new AesGcm(Key, 16);
        var appended = new byte[V1Datagram.Length + 10];
        V1Datagram.CopyTo(appended, 0);
        var nonce = (byte[])Nonce.Clone();
        var pcm = new byte[AudioPipeline.PacketPcmBytes];

        bool ok = AudioPipeline.TryDecrypt(aes, appended, nonce, pcm,
            out _, out _, out _);
        Assert.False(ok); // length check fails (not exactly 1000)
    }
}
